spring.application.name=auth-service
server.port=8081

spring.config.import=optional:file:../.env

# connexion bdd
spring.datasource.username=${AUTH_DB_USER}
spring.datasource.password=${AUTH_DB_PASSWORD}

spring.datasource.url=${AUTH_DB_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.jpa.hibernate.ddl-auto=update