services:
# --- BDD ----
  chat-db:
    image: postgres:16-alpine
    container_name: chat-database
    environment:
      POSTGRES_USER: ${CHAT_DB_USER}
      POSTGRES_PASSWORD: ${CHAT_DB_PASSWORD}
      POSTGRES_DB: chat_db
    ports:
      - "5433:5432"

  user-db:
    image: postgres:16-alpine
    container_name: user-database
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: keycloak
    ports:
      - "5434:5432"

# --- MICROSERVICES ---
  chat-api:
    build:
      context: ./chat-service
    container_name: chat-microservice
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      CHAT_DB_URL: jdbc:postgresql://chat-db:5432/chat_db
    depends_on:
      - chat-db

  user-api:
    build:
      context: ./user-service
    container_name: user-microservice
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      USER_DB_URL: jdbc:postgresql://user-db:5432/user_db
    depends_on:
      - user-db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-server
    command: start-dev --import-realm
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_URL: ${KEYCLOAK_PUBLIC_URL:-http://localhost:8085}
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8085:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - keycloak-db
  
  gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      CHAT_INTERNAL_URL: http://chat-api:8082
      USER_INTERNAL_URL: http://user-api:8081
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      KEYCLOAK_PUBLIC_URL: ${KEYCLOAK_PUBLIC_URL:-http://localhost:8085}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:4200}
    depends_on:
      - keycloak