server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: ${AUTH_INTERNAL_URL:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: chat-service-route
              uri: ${CHAT_INTERNAL_URL:http://localhost:8082}
              predicates:
                - Path=/api/chat/**
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"

security:
  jwt:
    secret-key: bW9uLXN1cGVyLXNlY3JldC1wb3VyLWxlcy1qd3QtZGUtbW9uLWFwcGxpY2F0aW9uLW1kZAo=
    access-token-expiration: 900000
    refresh-token-expiration: 604800000
