server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: bW9uLXN1cGVyLXNlY3JldC1wb3VyLWxlcy1qd3QtZGUtbW9uLWFwcGxpY2F0aW9uLW1kZAo=
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: http://localhost:8085/realms/microservices-realm/protocol/openid-connect/auth
            token-uri: ${KEYCLOAK_INTERNAL_URL:http://localhost:8085}/realms/microservices-realm/protocol/openid-connect/token
            jwk-set-uri: ${KEYCLOAK_INTERNAL_URL:http://localhost:8085}/realms/microservices-realm/protocol/openid-connect/certs
            user-info-uri: ${KEYCLOAK_INTERNAL_URL:http://localhost:8085}/realms/microservices-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: chat-service-route
              uri: ${CHAT_INTERNAL_URL:http://localhost:8082}
              predicates:
                - Path=/api/chat/**
              filters:
                - TokenRelay=
          globalcors:
            cors-configurations:
              "[/**]":
                allowedOrigins: "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
