spring.application.name=user-service
server.port=8081

spring.config.import=optional:file:../.env

# connexion bdd
spring.datasource.username=${USER_DB_USER}
spring.datasource.password=${USER_DB_PASSWORD}

spring.datasource.url=${USER_DB_URL:jdbc:postgresql://localhost:5432/user_db}
spring.jpa.hibernate.ddl-auto=validate