spring.application.name=chat-service
server.port=8082

spring.config.import=optional:file:../.env

# connexion bdd
spring.datasource.username=${CHAT_DB_USER}
spring.datasource.password=${CHAT_DB_PASSWORD}

spring.datasource.url=${CHAT_DB_URL:jdbc:postgresql://localhost:5432/chat_db}
spring.jpa.hibernate.ddl-auto=validate

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_INTERNAL_URL:http://localhost:8085}/realms/microservices-realm/protocol/openid-connect/certs

app.keycloak-issuer-uri:${KEYCLOAK_PUBLIC_URL:http://localhost:8085}/realms/microservices-realm